data:
  dir: "/storage/coda1/p-dsgt_clef2025/0/shared/checkthat-2025-numerical-data"
  train_claims_quantemp: "raw_data/train_claims_quantemp.json"
  train_claims_embedding: "embeddings/train_claims_embed"

encoder_model: 
  name: "answerdotai/ModernBERT-large"
  add_special_tokens: true
  padding: "max_length"
  truncation: true
  return_attention_mask: true
  return_tensors: "pt"
  pad_to_max_length: true
  max_length: 128
  batch_size: 20

dim_red_model:
  name: "pacmap"
  n_components: 2
  n_neighbors: 10
  MN_ratio: 0.5
  FP_ratio: 2.0

visualization:
  fig_dir: "/storage/coda1/p-dsgt_clef2025/0/shared/checkthat-2025-numerical-data/fig"
  data_type: "png"
  figure_size: [6, 6]